title: <p align="center"> Nataraj Naikar</p>
logo: /assets/img/unnamed.jpg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/natarajnaikar/">LinkedIn</a> |
  <a href="https://github.com/natrajnaikar">GitHub</a>
<br>   
  I'm on training to learn  Data Science, Big Data, Spark, Machine learning & NLP related problems.
  I am Product Manager and handling the creation technical artifacts in the area of AIML,BigData and Analytics.
  Working in Storage domain for 4 years.
  <br>
  </p>
theme: jekyll-theme-minimal


